# Generated by Django 5.0.6 on 2025-08-08 01:28

import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("bio", models.TextField(blank=True)),
                ("goals", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("availability_hrs_week", models.PositiveSmallIntegerField(default=10)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("founder", "Founder"),
                            ("joiner", "Joining a team"),
                            ("undecided", "Undecided"),
                        ],
                        max_length=32,
                    ),
                ),
                ("vector", pgvector.django.VectorField(dimensions=384, null=True)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interests",
                    models.ManyToManyField(blank=True, to="profiles.interest"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("skills", models.ManyToManyField(blank=True, to="profiles.skill")),
            ],
        ),
    ]
