# Generated by Django 5.0.6 on 2025-08-10 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("view", "view"),
                            ("like", "like"),
                            ("connect_req", "connect_req"),
                            ("connect_accept", "connect_accept"),
                            ("message", "message"),
                            ("reply", "reply"),
                            ("meeting", "meeting"),
                            ("collab_start", "collab_start"),
                            ("collab_end", "collab_end"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_out",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_in",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["actor", "target", "ts"],
                        name="interaction_actor_i_1a5342_idx",
                    )
                ],
            },
        ),
    ]
